### ISSUE TITLE
Can't open/read file: check file path/integrity

### ISSUE THREAD

**Issue by CodenameNoliP** [axlroden/stayin#3]
SUCCESS: The process "WowClassic.exe" with PID 2052 has been terminated.
[ WARN:0@11.629] global D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp (239) cv::findDecoder imread_('./data/change_realm_1440.png'): can't open/read file: check file path/integrity
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2032.0_x64__qbz5n2kfra8p0\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\NoliP\Desktop\stayin-main\src\automator.py", line 117, in run
    pos = imagesearch(self.change_realm_img)
  File "C:\Users\NoliP\Desktop\stayin-main\src\imagesearch.py", line 105, in imagesearch
    template.shape[::-1]
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by CodenameNoliP** [comment]
also requirements.txt misses one dependency needed to even run code above. I don't remember which tho.

**Comment by axlroden** [comment]
requirements file is a remnant from earlier, I use pipenv to install dependencies. 
Check my github workflow, or clone this repo to make github compile an exe for you if you do not know how to use python.
